<?php

/**
 * @file
 * Contains webform_location_provider_element.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\Entity\Webform;


const WEBFORM_ELEMENT_NAME = "wf_permissions_by_term_element";

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * {@inheritdoc}
 */
function webform_permissions_by_term_form_webform_settings_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  /* @var \Drupal\webform\WebformEntitySettingsForm $webform_settings_form
   * @var \Drupal\webform\WebformInterface $webform $webform */
  // Get the settings from the webform config entity.
  $webform_settings_form = $form_state->getFormObject();
  $webform = $webform_settings_form->getEntity();
  $webform_permissions_by_term_settings = $webform->getSetting('webform_permissions_by_term');

  // Get the default settings.
  $settings = webform_permissions_by_term_get_default_settings();
  // Loop through any settings set already and populate them.
  if (!empty($webform_permissions_by_term_settings)) {
    foreach ($webform_permissions_by_term_settings as $setting_name => $value) {
      $settings[$setting_name] = $value;
    }
  }

  // Add the twisty for wpbt.
  $form['webform_permissions_by_term'] = [
    '#type' => 'details',
    '#title' => 'Webform Permissions by Term',
    '#tree' => TRUE,
    '#weight' => -100,
  ];

  // Add the checkbox to enable/disable the security on this webform.
  $form['webform_permissions_by_term']['enable_webform_permissions_by_term'] = [
    '#type' => 'checkbox',
    '#title' => 'Enable Webform permissions by term',
    '#description' => 'If checked, this form will be secured by Taxonomy vocabulary.',
    '#return_value' => TRUE,
    '#default_value' => $settings['enable_webform_permissions_by_term'],
  ];


  //$webform_settings_form->getEntity()
}

/**
 * Get default settings for webform permissions by term.
 */
function webform_permissions_by_term_get_default_settings() {
  return [
    'enable_webform_permissions_by_term' => 0,
  ];
}

/**
 * Implements hook_webform_submission_form_alter().
 *
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function webform_permissions_by_term_webform_submission_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if(!is_webform_secured_by_term($form_state)) return;

  // Todo, if request is post, set the val
 //   $request = \Drupal::request();
//
//    if($request->getMethod() == 'POST'){
//      $cqclocationid = $request->get('cqclocationid');
//
//
//    } else {
//
//
//    }





}

function is_webform_secured_by_term(FormStateInterface $form_state){
  /* @var \Drupal\webform\WebformEntityForm $webform_settings_form
   * @var \Drupal\webform\Entity\Webform $webform $webform */
  // Get the settings from the webform config entity.

  $webform_settings_form = $form_state->getFormObject();
  $webform = $webform_settings_form->getEntity()->getWebform();

  $webform_permissions_by_term_settings = $webform->getSetting('webform_permissions_by_term');
  if(!empty($webform_permissions_by_term_settings)){
    if($webform_permissions_by_term_settings['enable_webform_permissions_by_term']) {
      return TRUE;
    }
  }
  return FALSE;
}

function is_webform_entity_secured_by_term(Webform $entity){
  // Get the settings from the webform config entity.
  $webform_permissions_by_term_settings = $entity->getSetting('webform_permissions_by_term');
  if(!empty($webform_permissions_by_term_settings)){
    if($webform_permissions_by_term_settings['enable_webform_permissions_by_term']) {
      return TRUE;
    }
  }
  return FALSE;
}

function does_webform_have_vocab_element(FormStateInterface $form_state){
  $element = $form_state->getFormObject()->getEntity()->getWebform()->getElementDecoded(WEBFORM_ELEMENT_NAME);

  if(!empty($element)){
    return TRUE;
  }
  return FALSE;
}

function get_webform_secured_by_term_vocab_machine_name(){
  return \Drupal::config('webform_permissions_by_term.settings.webform_permissions_by_term_vocab')->get('value');
}



/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function webform_permissions_by_term_webform_presave(Webform $entity) {
  $elements = $entity->getElementsDecoded();
  $has_security_element = array_key_exists(WEBFORM_ELEMENT_NAME, $elements);

  if(!is_webform_entity_secured_by_term($entity) && $has_security_element) {
    $entity->deleteElement(WEBFORM_ELEMENT_NAME);
    return;
  }
  if(!is_webform_entity_secured_by_term($entity)) return;
  if($has_security_element) return;

  $new_element = [
    '#type' => 'webform_entity_select',
    '#title' => 'DO NOT REMOVE-Permissions By term Element',
    '#short_title_service' => 'Location ID',
    '#target_type' => 'taxonomy_term',
    '#selection_handler' => 'default:taxonomy_term',
    '#selection_settings' => [
      'target_bundles' => [
        'services' => 'services'
      ]
    ]
  ];

  $elements[WEBFORM_ELEMENT_NAME] = $new_element;

  $entity->setElements($elements);

}
